"""Declarative base, naming convention, and shared column mixins.

The persistence layer lives beside the engine, not inside it: `website/logical/`
stays a pure function of its input, and these models are how the application tier
remembers systems, proofs, and (in future) searchable theorems.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit, deterministic constraint/index names. Without this the names are
# autogenerated and drift between tools, which shows up as spurious diffs when
# a migration tool compares the models against the database.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def uuid_pk_column() -> Mapped[uuid.UUID]:
    """A UUID primary key.

    Carries both a client-side default (`uuid4`) and a Postgres server default
    (`gen_random_uuid()`): the server default keeps the column DB-authoritative on
    Postgres, while the client default lets the same models create rows on SQLite
    (no `gen_random_uuid()` there) — which the systems-store round-trip test uses.

    A factory rather than a plain mixin so the fastapi-users-based models, which
    can't take the mixin (their base already defines `id`), can still share the
    exact same id strategy by overriding `id` with this.
    """
    return mapped_column(
        primary_key=True, default=uuid.uuid4, server_default=func.gen_random_uuid()
    )


class UUIDPrimaryKeyMixin:
    id: Mapped[uuid.UUID] = uuid_pk_column()


class TimestampMixin:
    """Created/updated timestamps, both defaulted server-side."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )
