# Generated by Django 3.0.7 on 2020-06-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalSystem',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystem')),
            ],
        ),
        migrations.CreateModel(
            name='StringPattern',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64)),
                ('pattern', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('text', models.CharField(default='', max_length=62)),
                ('variable_name', models.CharField(default='', max_length=32)),
                ('parent_tree', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Tree')),
                ('string_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.StringPattern')),
            ],
        ),
        migrations.CreateModel(
            name='RuleCondition',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=256)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Rule')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=32)),
                ('dependent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent', to='website.StringPattern')),
                ('string_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_pattern', to='website.StringPattern')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaDefinition',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('string_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.StringPattern')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystem')),
            ],
        ),
        migrations.AddField(
            model_name='formalsystem',
            name='string_pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.StringPattern'),
        ),
        migrations.CreateModel(
            name='Axiom',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystem')),
            ],
        ),
    ]
