# Generated by Django 3.0.7 on 2021-07-22 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderEntry',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofModel',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('proof', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True)),
                ('proof_text', models.TextField(default='')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('folder_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.FolderEntry')),
            ],
        ),
        migrations.CreateModel(
            name='ProofFolder',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('folder_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.FolderEntry')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('slug', models.CharField(blank=True, max_length=64, null=True)),
                ('first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormalSystemModel',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('formal_system', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True)),
                ('formal_system_text', models.TextField(default='')),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('inherits_from', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_by', to='website.FormalSystemModel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='folderentry',
            name='formal_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystemModel'),
        ),
        migrations.AddField(
            model_name='folderentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Profile'),
        ),
        migrations.AddField(
            model_name='folderentry',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='website.ProofFolder'),
        ),
    ]
