# Generated by Django 3.0.7 on 2020-06-20 08:54

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='axiom',
            name='name',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='axiom',
            name='string_pattern',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.StringPattern'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Definition',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('higher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='higher', to='website.StringPattern')),
                ('lower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='website.StringPattern')),
                ('string_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='def_string_pattern', to='website.StringPattern')),
            ],
        ),
    ]
