# Generated by Django 3.0.7 on 2021-07-22 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prooffolder',
            name='folder_entry',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.FolderEntry'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='folder_entry',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.FolderEntry'),
            preserve_default=False,
        ),
    ]
