# Generated by Django 3.0.7 on 2021-08-01 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210722_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderentry',
            name='formal_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='website.FormalSystemModel'),
        ),
    ]
