# Generated by Django 3.0.7 on 2020-06-20 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20200620_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='definition',
            old_name='higher',
            new_name='higher_pattern',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='lower',
        ),
        migrations.AddField(
            model_name='definition',
            name='lower_tree',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.Tree'),
            preserve_default=False,
        ),
    ]
