# Generated by Django 3.0.7 on 2020-06-21 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200620_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='lower_tree',
        ),
        migrations.AddField(
            model_name='definition',
            name='lower_pattern',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lower', to='website.StringPattern'),
            preserve_default=False,
        ),
    ]
