# Generated by Django 3.0.7 on 2021-08-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210801_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='prooffolder',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
