# Generated by Django 3.0.7 on 2020-06-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200621_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringpattern',
            name='skip_node',
            field=models.BooleanField(default=False),
        ),
    ]
