# Generated by Django 3.0.7 on 2021-08-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_prooffolder_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='proofmodel',
            name='references',
            field=models.ManyToManyField(to='website.ProofModel'),
        ),
    ]
