# Generated by Django 3.2.6 on 2021-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_proofmodel_references'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderentry',
            options={},
        ),
        migrations.AlterField(
            model_name='folderentry',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
