# Generated by Django 3.0.7 on 2020-06-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_stringpattern_skip_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='safe_slug',
            field=models.SlugField(default='', max_length=32),
        ),
    ]
