# Generated by Django 3.2.6 on 2021-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210822_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderentry',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='folderentry',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
