# Generated by Django 3.0.7 on 2020-06-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_label_safe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stringpattern',
            name='safe_slug',
            field=models.SlugField(default='', max_length=64),
        ),
    ]
