# Generated by Django 3.2.6 on 2021-08-27 10:01

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210822_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prooffolder',
            name='published',
        ),
        migrations.CreateModel(
            name='PublishedFolder',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('formal_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_folders', to='website.formalsystemmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profile')),
                ('root_folder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.prooffolder')),
            ],
        ),
    ]
