# Generated by Django 3.0.7 on 2020-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_stringpattern_safe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystem',
            name='slug',
            field=models.SlugField(default='propositional_logic', max_length=64),
            preserve_default=False,
        ),
    ]
