# Generated by Django 3.0.7 on 2020-07-04 10:55

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_formalsystem_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='formalsystem',
            name='string_pattern',
        ),
        migrations.AddField(
            model_name='formalsystem',
            name='formula_join_pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_join', to='website.StringPattern'),
        ),
        migrations.AddField(
            model_name='formalsystem',
            name='formula_pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula', to='website.StringPattern'),
        ),
        migrations.AddField(
            model_name='formalsystem',
            name='formula_set_pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formula_set', to='website.StringPattern'),
        ),
        migrations.AddField(
            model_name='formalsystem',
            name='proof_line_pattern',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proof_line', to='website.StringPattern'),
        ),
        migrations.CreateModel(
            name='ProofLine',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('valid', models.BooleanField(blank=True, default=None, null=True)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Proof')),
                ('references', models.ManyToManyField(to='website.ProofLine')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Rule')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Tree')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='proof',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystem'),
        ),
    ]
