# Generated by Django 3.2.6 on 2021-08-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210827_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='prooffolder',
            name='published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publishedfolder'),
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publishedfolder'),
        ),
    ]
