# Generated by Django 3.2.6 on 2021-08-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210828_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofmodel',
            name='references',
            field=models.ManyToManyField(related_name='dependants', to='website.ProofModel'),
        ),
    ]
