# Generated by Django 3.2.6 on 2021-09-05 11:03

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_proofmodel_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedEntry',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('published', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='website.folderentry')),
                ('formal_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_entries', to='website.formalsystemmodel')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='prooffolder',
            name='published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publishedentry'),
        ),
        migrations.AlterField(
            model_name='proofmodel',
            name='published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publishedentry'),
        ),
        migrations.DeleteModel(
            name='PublishedFolder',
        ),
    ]
