# Generated by Django 3.0.7 on 2020-12-24 14:46

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20201224_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormalSystemModel',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
