# Generated by Django 3.2.6 on 2021-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210905_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publishedentry',
            old_name='entry',
            new_name='folder_entry',
        ),
        migrations.RemoveField(
            model_name='publishedentry',
            name='formal_system',
        ),
        migrations.RemoveField(
            model_name='publishedentry',
            name='owner',
        ),
    ]
