# Generated by Django 3.0.7 on 2020-12-24 15:06

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_formalsystemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='formal_system',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
