# Generated by Django 3.0.7 on 2020-12-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_formalsystemmodel_formal_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='slug',
            field=models.CharField(default='propositional', max_length=64),
            preserve_default=False,
        ),
    ]
