# Generated by Django 3.2.6 on 2021-09-05 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210905_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prooffolder',
            name='published',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='published',
        ),
        migrations.AddField(
            model_name='folderentry',
            name='published',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.publishedentry'),
        ),
    ]
