# Generated by Django 3.0.7 on 2020-12-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_formalsystemmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsystemmodel',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
