# Generated by Django 3.2.6 on 2021-10-19 14:53

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210905_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folderentry',
            options={'verbose_name_plural': 'Folder entries'},
        ),
        migrations.AlterModelOptions(
            name='publishedentry',
            options={'verbose_name_plural': 'Published entries'},
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='unsaved_proof',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
