# Generated by Django 3.0.7 on 2020-12-28 11:54

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201227_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsystemmodel',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='formalsystemmodel',
            name='slug',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='ProofModel',
            fields=[
                ('id', models.CharField(default=website.models.id_gen, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('proof', picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('formal_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.FormalSystemModel')),
            ],
        ),
    ]
