# Generated by Django 3.0.7 on 2021-01-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20201228_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalsystemmodel',
            name='formal_system',
        ),
        migrations.RemoveField(
            model_name='proofmodel',
            name='proof',
        ),
    ]
