# Generated by Django 3.0.7 on 2021-01-10 09:14

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20210110_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='formal_system',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='proof',
            field=picklefield.fields.PickledObjectField(blank=True, default=None, editable=False, null=True),
        ),
    ]
