# Generated by Django 3.0.7 on 2021-05-16 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210110_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='axioms',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.ProofModel'),
        ),
    ]
