# Generated by Django 3.0.7 on 2021-05-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_formalsystemmodel_axioms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formalsystemmodel',
            name='axioms',
        ),
    ]
