# Generated by Django 3.0.7 on 2021-07-09 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20210708_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='inherits_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.FormalSystemModel'),
        ),
    ]
