# Generated by Django 3.0.7 on 2021-07-09 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_formalsystemmodel_inherits_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalsystemmodel',
            name='inherits_from',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inherited_by', to='website.FormalSystemModel'),
        ),
    ]
