# Generated by Django 3.0.7 on 2021-07-09 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20210709_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Profile'),
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Profile'),
        ),
    ]
