# Generated by Django 3.0.7 on 2021-07-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20210709_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
