# Generated by Django 3.0.7 on 2021-07-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20210716_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
