# Generated by Django 3.0.7 on 2021-07-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_auto_20210716_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalsystemmodel',
            name='formal_system_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proofmodel',
            name='proof_text',
            field=models.TextField(default=''),
        ),
    ]
