-- Normalise primary-key constraint names to the app/db naming convention
-- (`pk_<table>`). The initial baseline was generated by an unauthenticated Atlas,
-- which emitted inline unnamed primary keys — Postgres then defaulted them to
-- `<table>_pkey`, diverging from the convention the models declare. This aligns
-- the database with the models (the source of truth) for stable, tool-agnostic
-- constraint names.
-- Rename a constraint from "axiom_bindings_pkey" to "pk_axiom_bindings"
ALTER TABLE "public"."axiom_bindings" RENAME CONSTRAINT "axiom_bindings_pkey" TO "pk_axiom_bindings";
-- Rename a constraint from "axioms_pkey" to "pk_axioms"
ALTER TABLE "public"."axioms" RENAME CONSTRAINT "axioms_pkey" TO "pk_axioms";
-- Rename a constraint from "definition_bindings_pkey" to "pk_definition_bindings"
ALTER TABLE "public"."definition_bindings" RENAME CONSTRAINT "definition_bindings_pkey" TO "pk_definition_bindings";
-- Rename a constraint from "definitions_pkey" to "pk_definitions"
ALTER TABLE "public"."definitions" RENAME CONSTRAINT "definitions_pkey" TO "pk_definitions";
-- Rename a constraint from "formal_systems_pkey" to "pk_formal_systems"
ALTER TABLE "public"."formal_systems" RENAME CONSTRAINT "formal_systems_pkey" TO "pk_formal_systems";
-- Rename a constraint from "line_parts_pkey" to "pk_line_parts"
ALTER TABLE "public"."line_parts" RENAME CONSTRAINT "line_parts_pkey" TO "pk_line_parts";
-- Rename a constraint from "line_types_pkey" to "pk_line_types"
ALTER TABLE "public"."line_types" RENAME CONSTRAINT "line_types_pkey" TO "pk_line_types";
-- Rename a constraint from "notation_brackets_pkey" to "pk_notation_brackets"
ALTER TABLE "public"."notation_brackets" RENAME CONSTRAINT "notation_brackets_pkey" TO "pk_notation_brackets";
-- Rename a constraint from "oauth_accounts_pkey" to "pk_oauth_accounts"
ALTER TABLE "public"."oauth_accounts" RENAME CONSTRAINT "oauth_accounts_pkey" TO "pk_oauth_accounts";
-- Rename a constraint from "production_bindings_pkey" to "pk_production_bindings"
ALTER TABLE "public"."production_bindings" RENAME CONSTRAINT "production_bindings_pkey" TO "pk_production_bindings";
-- Rename a constraint from "productions_pkey" to "pk_productions"
ALTER TABLE "public"."productions" RENAME CONSTRAINT "productions_pkey" TO "pk_productions";
-- Rename a constraint from "proof_folders_pkey" to "pk_proof_folders"
ALTER TABLE "public"."proof_folders" RENAME CONSTRAINT "proof_folders_pkey" TO "pk_proof_folders";
-- Rename a constraint from "proof_references_pkey" to "pk_proof_references"
ALTER TABLE "public"."proof_references" RENAME CONSTRAINT "proof_references_pkey" TO "pk_proof_references";
-- Rename a constraint from "proofs_pkey" to "pk_proofs"
ALTER TABLE "public"."proofs" RENAME CONSTRAINT "proofs_pkey" TO "pk_proofs";
-- Rename a constraint from "rule_antecedents_pkey" to "pk_rule_antecedents"
ALTER TABLE "public"."rule_antecedents" RENAME CONSTRAINT "rule_antecedents_pkey" TO "pk_rule_antecedents";
-- Rename a constraint from "rule_bindings_pkey" to "pk_rule_bindings"
ALTER TABLE "public"."rule_bindings" RENAME CONSTRAINT "rule_bindings_pkey" TO "pk_rule_bindings";
-- Rename a constraint from "rules_pkey" to "pk_rules"
ALTER TABLE "public"."rules" RENAME CONSTRAINT "rules_pkey" TO "pk_rules";
-- Rename a constraint from "sorts_pkey" to "pk_sorts"
ALTER TABLE "public"."sorts" RENAME CONSTRAINT "sorts_pkey" TO "pk_sorts";
-- Rename a constraint from "theorems_pkey" to "pk_theorems"
ALTER TABLE "public"."theorems" RENAME CONSTRAINT "theorems_pkey" TO "pk_theorems";
-- Rename a constraint from "users_pkey" to "pk_users"
ALTER TABLE "public"."users" RENAME CONSTRAINT "users_pkey" TO "pk_users";
