"""initial schema

Revision ID: 18fbd4863856
Revises: 
Create Date: 2026-08-19 21:08:42.495292

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = '18fbd4863856'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Hand-added: autogenerate does not emit extensions. `vector` types the
    # `theorems.embedding` column and its HNSW index; `pg_trgm` provides the
    # `gin_trgm_ops` operator class the prose-search indexes below are built
    # with. Both must exist before the tables that use them.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('formal_systems',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('inherits_from_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_separated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inherits_from_id'], ['formal_systems.id'], name=op.f('fk_formal_systems_inherits_from_id_formal_systems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_formal_systems_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formal_systems'))
    )
    op.create_index(op.f('ix_formal_systems_inherits_from_id'), 'formal_systems', ['inherits_from_id'], unique=False)
    op.create_index(op.f('ix_formal_systems_owner_id'), 'formal_systems', ['owner_id'], unique=False)
    op.create_index(op.f('ix_formal_systems_slug'), 'formal_systems', ['slug'], unique=False)
    op.create_index('uq_formal_systems_owner_slug', 'formal_systems', ['owner_id', 'slug'], unique=True, postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.create_table('oauth_accounts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts'))
    )
    op.create_index(op.f('ix_oauth_accounts_account_id'), 'oauth_accounts', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_oauth_name'), 'oauth_accounts', ['oauth_name'], unique=False)
    op.create_index(op.f('ix_oauth_accounts_user_id'), 'oauth_accounts', ['user_id'], unique=False)
    op.create_table('source_documents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('identifier', sa.String(length=512), nullable=False),
    sa.Column('version', sa.String(length=64), server_default='', nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('licence', sa.String(length=128), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registered_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registered_by_id'], ['users.id'], name=op.f('fk_source_documents_registered_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents'))
    )
    op.create_index(op.f('ix_source_documents_registered_by_id'), 'source_documents', ['registered_by_id'], unique=False)
    op.create_index('uq_source_documents_identity', 'source_documents', ['kind', 'identifier', 'version'], unique=True)
    op.create_table('axioms',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('formula', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_axioms_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_axioms'))
    )
    op.create_index(op.f('ix_axioms_label'), 'axioms', ['label'], unique=False)
    op.create_index(op.f('ix_axioms_name'), 'axioms', ['name'], unique=False)
    op.create_index(op.f('ix_axioms_system_id'), 'axioms', ['system_id'], unique=False)
    op.create_table('label_claims',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('object', sa.String(length=128), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_label_claims_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_claims'))
    )
    op.create_index(op.f('ix_label_claims_formal_system_id'), 'label_claims', ['formal_system_id'], unique=False)
    op.create_index('ix_label_claims_object_kind', 'label_claims', ['object', 'kind'], unique=False)
    op.create_index('ix_label_claims_system_subject', 'label_claims', ['formal_system_id', 'subject'], unique=False)
    op.create_table('label_descriptions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), server_default='', nullable=False),
    sa.Column('discouraged_usage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('discouraged_modification', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_label_descriptions_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_descriptions'))
    )
    op.create_index(op.f('ix_label_descriptions_formal_system_id'), 'label_descriptions', ['formal_system_id'], unique=False)
    op.create_index('ix_label_descriptions_label_trgm', 'label_descriptions', ['label'], unique=False, postgresql_using='gin', postgresql_ops={'label': 'gin_trgm_ops'})
    op.create_index('ix_label_descriptions_text_trgm', 'label_descriptions', ['text'], unique=False, postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.create_index('ix_label_descriptions_title_trgm', 'label_descriptions', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('uq_label_descriptions_system_label', 'label_descriptions', ['formal_system_id', 'label'], unique=True)
    op.create_table('notation_brackets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('opening', sa.String(length=16), nullable=False),
    sa.Column('closing', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_notation_brackets_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notation_brackets'))
    )
    op.create_index(op.f('ix_notation_brackets_system_id'), 'notation_brackets', ['system_id'], unique=False)
    op.create_table('notation_pieces',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('notation', sa.String(length=64), nullable=False),
    sa.Column('constructor', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_notation_pieces_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notation_pieces'))
    )
    op.create_index(op.f('ix_notation_pieces_formal_system_id'), 'notation_pieces', ['formal_system_id'], unique=False)
    op.create_index('uq_notation_pieces_system_notation_constructor_position', 'notation_pieces', ['formal_system_id', 'notation', 'constructor', 'position'], unique=True)
    op.create_table('notation_rules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('notation', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('constructor', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_notation_rules_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notation_rules'))
    )
    op.create_index(op.f('ix_notation_rules_constructor'), 'notation_rules', ['constructor'], unique=False)
    op.create_index(op.f('ix_notation_rules_formal_system_id'), 'notation_rules', ['formal_system_id'], unique=False)
    op.create_index('uq_notation_rules_system_notation_name', 'notation_rules', ['formal_system_id', 'notation', 'name'], unique=True)
    op.create_table('proof_folders',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_proof_folders_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_proof_folders_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['proof_folders.id'], name=op.f('fk_proof_folders_parent_id_proof_folders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_folders'))
    )
    op.create_index(op.f('ix_proof_folders_formal_system_id'), 'proof_folders', ['formal_system_id'], unique=False)
    op.create_index(op.f('ix_proof_folders_owner_id'), 'proof_folders', ['owner_id'], unique=False)
    op.create_index(op.f('ix_proof_folders_parent_id'), 'proof_folders', ['parent_id'], unique=False)
    op.create_index(op.f('ix_proof_folders_slug'), 'proof_folders', ['slug'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('template', sa.String(length=512), nullable=True),
    sa.Column('regex', sa.Text(), nullable=True),
    sa.Column('atom_value', sa.String(length=512), nullable=True),
    sa.Column('atom_base', sa.String(length=128), nullable=True),
    sa.Column('denotes_constant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('member_of_union_id', sa.Uuid(), nullable=True),
    sa.Column('inclusion_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_of_union_id'], ['symbols.id'], name=op.f('fk_symbols_member_of_union_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_symbols_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_symbols'))
    )
    op.create_index(op.f('ix_symbols_member_of_union_id'), 'symbols', ['member_of_union_id'], unique=False)
    op.create_index(op.f('ix_symbols_name'), 'symbols', ['name'], unique=False)
    op.create_index(op.f('ix_symbols_system_id'), 'symbols', ['system_id'], unique=False)
    op.create_index('uq_symbols_system_name', 'symbols', ['system_id', 'name'], unique=True)
    op.create_table('system_relations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_system_id', sa.Uuid(), nullable=False),
    sa.Column('target_system_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default=sa.text("'extension'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('statement_template', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['source_system_id'], ['formal_systems.id'], name=op.f('fk_system_relations_source_system_id_formal_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_system_id'], ['formal_systems.id'], name=op.f('fk_system_relations_target_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_relations'))
    )
    op.create_index(op.f('ix_system_relations_source_system_id'), 'system_relations', ['source_system_id'], unique=False)
    op.create_index('ix_system_relations_target_status', 'system_relations', ['target_system_id', 'status'], unique=False)
    op.create_index(op.f('ix_system_relations_target_system_id'), 'system_relations', ['target_system_id'], unique=False)
    op.create_index('uq_system_relations_source_target', 'system_relations', ['source_system_id', 'target_system_id'], unique=True)
    op.create_table('terms',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('constructor', sa.String(length=512), nullable=True),
    sa.Column('literal', sa.String(length=512), nullable=True),
    sa.Column('sort', sa.String(length=128), nullable=True),
    sa.Column('var_name', sa.String(length=128), nullable=True),
    sa.Column('bound_index', sa.Integer(), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('alpha_digest', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_terms_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms'))
    )
    op.create_index(op.f('ix_terms_formal_system_id'), 'terms', ['formal_system_id'], unique=False)
    op.create_index(op.f('ix_terms_literal'), 'terms', ['literal'], unique=False)
    op.create_index('ix_terms_system_alpha_digest', 'terms', ['formal_system_id', 'alpha_digest'], unique=False)
    op.create_index('ix_terms_system_constructor', 'terms', ['formal_system_id', 'constructor'], unique=False)
    op.create_index('uq_terms_system_digest', 'terms', ['formal_system_id', 'digest'], unique=True)
    op.create_table('axiom_bindings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('axiom_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['axiom_id'], ['axioms.id'], name=op.f('fk_axiom_bindings_axiom_id_axioms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_axiom_bindings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_axiom_bindings'))
    )
    op.create_index(op.f('ix_axiom_bindings_axiom_id'), 'axiom_bindings', ['axiom_id'], unique=False)
    op.create_index(op.f('ix_axiom_bindings_symbol_id'), 'axiom_bindings', ['symbol_id'], unique=False)
    op.create_table('definitions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('higher', sa.String(length=512), nullable=False),
    sa.Column('lower', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('justification_label', sa.String(length=64), nullable=True),
    sa.Column('justification_statement', sa.String(length=512), nullable=True),
    sa.Column('term_digest', sa.String(length=64), nullable=True),
    sa.Column('higher_term_id', sa.Uuid(), nullable=True),
    sa.Column('lower_term_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['higher_term_id'], ['terms.id'], name=op.f('fk_definitions_higher_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lower_term_id'], ['terms.id'], name=op.f('fk_definitions_lower_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_definitions_symbol_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_definitions_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_definitions'))
    )
    op.create_index(op.f('ix_definitions_higher_term_id'), 'definitions', ['higher_term_id'], unique=False)
    op.create_index(op.f('ix_definitions_lower_term_id'), 'definitions', ['lower_term_id'], unique=False)
    op.create_index(op.f('ix_definitions_name'), 'definitions', ['name'], unique=False)
    op.create_index(op.f('ix_definitions_symbol_id'), 'definitions', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_definitions_system_id'), 'definitions', ['system_id'], unique=False)
    op.create_table('label_attributions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('who', sa.String(length=128), nullable=False),
    sa.Column('dated', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['label_descriptions.id'], name=op.f('fk_label_attributions_description_id_label_descriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_attributions'))
    )
    op.create_index(op.f('ix_label_attributions_description_id'), 'label_attributions', ['description_id'], unique=False)
    op.create_index(op.f('ix_label_attributions_kind'), 'label_attributions', ['kind'], unique=False)
    op.create_index(op.f('ix_label_attributions_who'), 'label_attributions', ['who'], unique=False)
    op.create_table('label_citations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('work', sa.String(length=64), nullable=False),
    sa.Column('page', sa.String(length=32), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['label_descriptions.id'], name=op.f('fk_label_citations_description_id_label_descriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_citations'))
    )
    op.create_index(op.f('ix_label_citations_description_id'), 'label_citations', ['description_id'], unique=False)
    op.create_index('ix_label_citations_work', 'label_citations', ['work'], unique=False)
    op.create_table('label_references',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('description_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=False),
    sa.Column('end_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['description_id'], ['label_descriptions.id'], name=op.f('fk_label_references_description_id_label_descriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label_references'))
    )
    op.create_index(op.f('ix_label_references_description_id'), 'label_references', ['description_id'], unique=False)
    op.create_index('ix_label_references_target', 'label_references', ['target'], unique=False)
    op.create_table('line_types',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('shape', sa.String(length=256), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('behaviour', sa.String(length=16), server_default=sa.text("'logical'"), nullable=False),
    sa.Column('logical_symbol_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['logical_symbol_id'], ['symbols.id'], name=op.f('fk_line_types_logical_symbol_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_line_types_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_types'))
    )
    op.create_index(op.f('ix_line_types_logical_symbol_id'), 'line_types', ['logical_symbol_id'], unique=False)
    op.create_index(op.f('ix_line_types_system_id'), 'line_types', ['system_id'], unique=False)
    op.create_table('notation_rule_pieces',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('text', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['notation_rules.id'], name=op.f('fk_notation_rule_pieces_rule_id_notation_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notation_rule_pieces'))
    )
    op.create_index(op.f('ix_notation_rule_pieces_rule_id'), 'notation_rule_pieces', ['rule_id'], unique=False)
    op.create_index('uq_notation_rule_pieces_rule_position', 'notation_rule_pieces', ['rule_id', 'position'], unique=True)
    op.create_table('notation_rule_pins',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(length=512), nullable=False),
    sa.Column('constructor', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['notation_rules.id'], name=op.f('fk_notation_rule_pins_rule_id_notation_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notation_rule_pins'))
    )
    op.create_index(op.f('ix_notation_rule_pins_rule_id'), 'notation_rule_pins', ['rule_id'], unique=False)
    op.create_index('uq_notation_rule_pins_rule_slot', 'notation_rule_pins', ['rule_id', 'slot'], unique=True)
    op.create_table('production_bindings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('production_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['symbols.id'], name=op.f('fk_production_bindings_production_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_production_bindings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_bindings'))
    )
    op.create_index(op.f('ix_production_bindings_production_id'), 'production_bindings', ['production_id'], unique=False)
    op.create_index(op.f('ix_production_bindings_symbol_id'), 'production_bindings', ['symbol_id'], unique=False)
    op.create_table('promoted_theorems',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('primitive', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('matching', sa.String(length=16), server_default=sa.text("'structural'"), nullable=False),
    sa.Column('statement_term_id', sa.Uuid(), nullable=True),
    sa.Column('schema_digest', sa.String(length=64), nullable=True),
    sa.Column('conclusion_fingerprint', sa.Text(), nullable=True),
    sa.Column('proved_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['statement_term_id'], ['terms.id'], name=op.f('fk_promoted_theorems_statement_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_promoted_theorems_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promoted_theorems'))
    )
    op.create_index(op.f('ix_promoted_theorems_label'), 'promoted_theorems', ['label'], unique=False)
    op.create_index(op.f('ix_promoted_theorems_proved_by_id'), 'promoted_theorems', ['proved_by_id'], unique=False)
    op.create_index(op.f('ix_promoted_theorems_statement_term_id'), 'promoted_theorems', ['statement_term_id'], unique=False)
    op.create_index(op.f('ix_promoted_theorems_system_id'), 'promoted_theorems', ['system_id'], unique=False)
    op.create_index('ix_promoted_theorems_system_primitive', 'promoted_theorems', ['system_id', 'primitive'], unique=False)
    op.create_index('uq_promoted_theorems_system_label', 'promoted_theorems', ['system_id', 'label'], unique=True)
    op.create_table('rules',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('system_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('deduction', sa.String(length=512), nullable=False),
    sa.Column('matching', sa.String(length=16), server_default=sa.text("'structural'"), nullable=False),
    sa.Column('subproof_derive', sa.String(length=512), nullable=True),
    sa.Column('subproof_assume', sa.String(length=512), nullable=True),
    sa.Column('subproof_fresh', sa.String(length=512), nullable=True),
    sa.Column('allow_extra_antecedents', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('schema_digest', sa.String(length=64), nullable=True),
    sa.Column('deduction_term_id', sa.Uuid(), nullable=True),
    sa.Column('subproof_derive_term_id', sa.Uuid(), nullable=True),
    sa.Column('subproof_assume_term_id', sa.Uuid(), nullable=True),
    sa.Column('subproof_fresh_term_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['deduction_term_id'], ['terms.id'], name=op.f('fk_rules_deduction_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subproof_assume_term_id'], ['terms.id'], name=op.f('fk_rules_subproof_assume_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subproof_derive_term_id'], ['terms.id'], name=op.f('fk_rules_subproof_derive_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subproof_fresh_term_id'], ['terms.id'], name=op.f('fk_rules_subproof_fresh_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id'], ['formal_systems.id'], name=op.f('fk_rules_system_id_formal_systems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rules'))
    )
    op.create_index(op.f('ix_rules_deduction_term_id'), 'rules', ['deduction_term_id'], unique=False)
    op.create_index(op.f('ix_rules_label'), 'rules', ['label'], unique=False)
    op.create_index(op.f('ix_rules_name'), 'rules', ['name'], unique=False)
    op.create_index(op.f('ix_rules_subproof_assume_term_id'), 'rules', ['subproof_assume_term_id'], unique=False)
    op.create_index(op.f('ix_rules_subproof_derive_term_id'), 'rules', ['subproof_derive_term_id'], unique=False)
    op.create_index(op.f('ix_rules_subproof_fresh_term_id'), 'rules', ['subproof_fresh_term_id'], unique=False)
    op.create_index(op.f('ix_rules_system_id'), 'rules', ['system_id'], unique=False)
    op.create_table('system_relation_extras',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['system_relations.id'], name=op.f('fk_system_relation_extras_relation_id_system_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_relation_extras'))
    )
    op.create_index(op.f('ix_system_relation_extras_relation_id'), 'system_relation_extras', ['relation_id'], unique=False)
    op.create_index('uq_system_relation_extras_name', 'system_relation_extras', ['relation_id', 'name'], unique=True)
    op.create_table('system_relation_sorts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_sort', sa.String(length=128), nullable=False),
    sa.Column('target_sort', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['system_relations.id'], name=op.f('fk_system_relation_sorts_relation_id_system_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_relation_sorts'))
    )
    op.create_index(op.f('ix_system_relation_sorts_relation_id'), 'system_relation_sorts', ['relation_id'], unique=False)
    op.create_index('uq_system_relation_sorts_source', 'system_relation_sorts', ['relation_id', 'source_sort'], unique=True)
    op.create_table('system_relation_symbols',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_symbol', sa.String(length=128), nullable=False),
    sa.Column('target_symbol', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['relation_id'], ['system_relations.id'], name=op.f('fk_system_relation_symbols_relation_id_system_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_relation_symbols'))
    )
    op.create_index(op.f('ix_system_relation_symbols_relation_id'), 'system_relation_symbols', ['relation_id'], unique=False)
    op.create_index('uq_system_relation_symbols_source', 'system_relation_symbols', ['relation_id', 'source_symbol'], unique=True)
    op.create_table('term_children',
    sa.Column('parent_id', sa.Uuid(), nullable=False),
    sa.Column('slot', sa.String(length=128), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('child_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['terms.id'], name=op.f('fk_term_children_child_id_terms')),
    sa.ForeignKeyConstraint(['parent_id'], ['terms.id'], name=op.f('fk_term_children_parent_id_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'slot', name=op.f('pk_term_children'))
    )
    op.create_index(op.f('ix_term_children_child_id'), 'term_children', ['child_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('theorem_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('asserted_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asserted_by_id'], ['users.id'], name=op.f('fk_assumptions_asserted_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_assumptions_theorem_id_promoted_theorems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theorem_id', name=op.f('pk_assumptions'))
    )
    op.create_index(op.f('ix_assumptions_asserted_by_id'), 'assumptions', ['asserted_by_id'], unique=False)
    op.create_table('definition_bindings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definitions.id'], name=op.f('fk_definition_bindings_definition_id_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_definition_bindings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_definition_bindings'))
    )
    op.create_index(op.f('ix_definition_bindings_definition_id'), 'definition_bindings', ['definition_id'], unique=False)
    op.create_index(op.f('ix_definition_bindings_symbol_id'), 'definition_bindings', ['symbol_id'], unique=False)
    op.create_table('definition_fresh',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['definitions.id'], name=op.f('fk_definition_fresh_definition_id_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_definition_fresh_symbol_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_definition_fresh_term_id_terms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_definition_fresh'))
    )
    op.create_index(op.f('ix_definition_fresh_definition_id'), 'definition_fresh', ['definition_id'], unique=False)
    op.create_index(op.f('ix_definition_fresh_symbol_id'), 'definition_fresh', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_definition_fresh_term_id'), 'definition_fresh', ['term_id'], unique=False)
    op.create_table('line_parts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('regex', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['line_id'], ['line_types.id'], name=op.f('fk_line_parts_line_id_line_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_line_parts'))
    )
    op.create_index(op.f('ix_line_parts_line_id'), 'line_parts', ['line_id'], unique=False)
    op.create_table('production_binding_scopes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('binding_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('scoped_binding_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['binding_id'], ['production_bindings.id'], name=op.f('fk_production_binding_scopes_binding_id_production_bindings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scoped_binding_id'], ['production_bindings.id'], name=op.f('fk_production_binding_scopes_scoped_binding_id_production_bindings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_production_binding_scopes'))
    )
    op.create_index(op.f('ix_production_binding_scopes_binding_id'), 'production_binding_scopes', ['binding_id'], unique=False)
    op.create_index(op.f('ix_production_binding_scopes_scoped_binding_id'), 'production_binding_scopes', ['scoped_binding_id'], unique=False)
    op.create_table('promoted_theorem_bindings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('theorem_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=128), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_promoted_theorem_bindings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_promoted_theorem_bindings_theorem_id_promoted_theorems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promoted_theorem_bindings'))
    )
    op.create_index(op.f('ix_promoted_theorem_bindings_symbol_id'), 'promoted_theorem_bindings', ['symbol_id'], unique=False)
    op.create_index(op.f('ix_promoted_theorem_bindings_theorem_id'), 'promoted_theorem_bindings', ['theorem_id'], unique=False)
    op.create_table('promoted_theorem_premises',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('theorem_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_promoted_theorem_premises_term_id_terms'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_promoted_theorem_premises_theorem_id_promoted_theorems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promoted_theorem_premises'))
    )
    op.create_index(op.f('ix_promoted_theorem_premises_term_id'), 'promoted_theorem_premises', ['term_id'], unique=False)
    op.create_index(op.f('ix_promoted_theorem_premises_theorem_id'), 'promoted_theorem_premises', ['theorem_id'], unique=False)
    op.create_table('proofs',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=256), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('citations_stored', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('theorem_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['proof_folders.id'], name=op.f('fk_proofs_folder_id_proof_folders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_proofs_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_proofs_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_proofs_theorem_id_promoted_theorems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proofs'))
    )
    op.create_index('ix_proofs_description_trgm', 'proofs', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index(op.f('ix_proofs_folder_id'), 'proofs', ['folder_id'], unique=False)
    op.create_index(op.f('ix_proofs_formal_system_id'), 'proofs', ['formal_system_id'], unique=False)
    op.create_index('ix_proofs_name_trgm', 'proofs', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_proofs_owner_id'), 'proofs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_proofs_slug'), 'proofs', ['slug'], unique=False)
    op.create_index(op.f('ix_proofs_theorem_id'), 'proofs', ['theorem_id'], unique=False)
    op.create_index('ix_proofs_title_trgm', 'proofs', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('rule_antecedents',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('pattern', sa.String(length=512), nullable=False),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_antecedents_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_rule_antecedents_term_id_terms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_antecedents'))
    )
    op.create_index(op.f('ix_rule_antecedents_rule_id'), 'rule_antecedents', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_antecedents_term_id'), 'rule_antecedents', ['term_id'], unique=False)
    op.create_table('rule_bindings',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('var', sa.String(length=64), nullable=False),
    sa.Column('symbol_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_rule_bindings_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name=op.f('fk_rule_bindings_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rule_bindings'))
    )
    op.create_index(op.f('ix_rule_bindings_rule_id'), 'rule_bindings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_rule_bindings_symbol_id'), 'rule_bindings', ['symbol_id'], unique=False)
    op.create_table('side_conditions',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('promoted_theorem_id', sa.Uuid(), nullable=True),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('left_name', sa.String(length=512), nullable=True),
    sa.Column('right_name', sa.String(length=512), nullable=True),
    sa.Column('left_is_term', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('right_is_term', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_symbol_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint('(definition_id IS NOT NULL AND rule_id IS NULL AND promoted_theorem_id IS NULL) OR (definition_id IS NULL AND rule_id IS NOT NULL AND promoted_theorem_id IS NULL) OR (definition_id IS NULL AND rule_id IS NULL AND promoted_theorem_id IS NOT NULL)', name=op.f('ck_side_conditions_one_owner')),
    sa.ForeignKeyConstraint(['definition_id'], ['definitions.id'], name=op.f('fk_side_conditions_definition_id_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['side_conditions.id'], name=op.f('fk_side_conditions_parent_id_side_conditions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promoted_theorem_id'], ['promoted_theorems.id'], name=op.f('fk_side_conditions_promoted_theorem_id_promoted_theorems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], name=op.f('fk_side_conditions_rule_id_rules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sort_symbol_id'], ['symbols.id'], name=op.f('fk_side_conditions_sort_symbol_id_symbols'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_side_conditions'))
    )
    op.create_index(op.f('ix_side_conditions_definition_id'), 'side_conditions', ['definition_id'], unique=False)
    op.create_index('ix_side_conditions_definition_kind', 'side_conditions', ['definition_id', 'kind'], unique=False)
    op.create_index(op.f('ix_side_conditions_parent_id'), 'side_conditions', ['parent_id'], unique=False)
    op.create_index(op.f('ix_side_conditions_promoted_theorem_id'), 'side_conditions', ['promoted_theorem_id'], unique=False)
    op.create_index(op.f('ix_side_conditions_rule_id'), 'side_conditions', ['rule_id'], unique=False)
    op.create_index('ix_side_conditions_rule_kind', 'side_conditions', ['rule_id', 'kind'], unique=False)
    op.create_index(op.f('ix_side_conditions_sort_symbol_id'), 'side_conditions', ['sort_symbol_id'], unique=False)
    op.create_index('uq_side_conditions_definition_root', 'side_conditions', ['definition_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.create_index('uq_side_conditions_promoted_theorem_root', 'side_conditions', ['promoted_theorem_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.create_index('uq_side_conditions_rule_root', 'side_conditions', ['rule_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.create_table('system_relation_obligations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('relation_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('source_label', sa.String(length=128), nullable=False),
    sa.Column('discharged_by_primitive', sa.String(length=128), nullable=True),
    sa.Column('discharged_by_theorem_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'draft'"), nullable=False),
    sa.ForeignKeyConstraint(['discharged_by_theorem_id'], ['promoted_theorems.id'], name=op.f('fk_system_relation_obligations_discharged_by_theorem_id_promoted_theorems'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['relation_id'], ['system_relations.id'], name=op.f('fk_system_relation_obligations_relation_id_system_relations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_relation_obligations'))
    )
    op.create_index(op.f('ix_system_relation_obligations_discharged_by_theorem_id'), 'system_relation_obligations', ['discharged_by_theorem_id'], unique=False)
    op.create_index(op.f('ix_system_relation_obligations_relation_id'), 'system_relation_obligations', ['relation_id'], unique=False)
    op.create_index('uq_system_relation_obligations_label', 'system_relation_obligations', ['relation_id', 'source_label'], unique=True)
    op.create_table('theorem_assumptions',
    sa.Column('theorem_id', sa.Uuid(), nullable=False),
    sa.Column('assumption_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['promoted_theorems.id'], name=op.f('fk_theorem_assumptions_assumption_id_promoted_theorems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_theorem_assumptions_theorem_id_promoted_theorems'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('theorem_id', 'assumption_id', name=op.f('pk_theorem_assumptions'))
    )
    op.create_index('ix_theorem_assumptions_assumption', 'theorem_assumptions', ['assumption_id'], unique=False)
    op.create_table('formalizations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('claim', sa.String(length=256), nullable=False),
    sa.Column('informal_statement', sa.Text(), nullable=False),
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('statement_term_id', sa.Uuid(), nullable=False),
    sa.Column('proof_id', sa.Uuid(), nullable=True),
    sa.Column('attested_by_id', sa.Uuid(), nullable=True),
    sa.Column('attested_as', sa.String(length=128), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('review_verdict', sa.String(length=16), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attested_by_id'], ['users.id'], name=op.f('fk_formalizations_attested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['source_documents.id'], name=op.f('fk_formalizations_document_id_source_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_formalizations_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], name=op.f('fk_formalizations_proof_id_proofs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name=op.f('fk_formalizations_reviewed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_term_id'], ['terms.id'], name=op.f('fk_formalizations_statement_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formalizations'))
    )
    op.create_index(op.f('ix_formalizations_attested_by_id'), 'formalizations', ['attested_by_id'], unique=False)
    op.create_index(op.f('ix_formalizations_document_id'), 'formalizations', ['document_id'], unique=False)
    op.create_index(op.f('ix_formalizations_formal_system_id'), 'formalizations', ['formal_system_id'], unique=False)
    op.create_index(op.f('ix_formalizations_proof_id'), 'formalizations', ['proof_id'], unique=False)
    op.create_index(op.f('ix_formalizations_reviewed_by_id'), 'formalizations', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_formalizations_statement_term_id'), 'formalizations', ['statement_term_id'], unique=False)
    op.create_table('proof_lines',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('proof_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('indent', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('display', sa.Text(), server_default='', nullable=False),
    sa.Column('line_type', sa.String(length=256), nullable=True),
    sa.Column('behaviour', sa.String(length=32), nullable=True),
    sa.Column('label', sa.String(length=256), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('rule', sa.String(length=256), nullable=True),
    sa.Column('theorem_id', sa.Uuid(), nullable=True),
    sa.Column('definition_id', sa.Uuid(), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('valid', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('invalid_message', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=32), nullable=True),
    sa.Column('failure_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('warning_message', sa.Text(), nullable=True),
    sa.Column('opens_scope', sa.String(length=32), nullable=True),
    sa.Column('scope_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['definitions.id'], name=op.f('fk_proof_lines_definition_id_definitions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], name=op.f('fk_proof_lines_proof_id_proofs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['proof_lines.id'], name=op.f('fk_proof_lines_scope_id_proof_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_proof_lines_term_id_terms')),
    sa.ForeignKeyConstraint(['theorem_id'], ['promoted_theorems.id'], name=op.f('fk_proof_lines_theorem_id_promoted_theorems'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proof_lines'))
    )
    op.create_index(op.f('ix_proof_lines_definition_id'), 'proof_lines', ['definition_id'], unique=False)
    op.create_index(op.f('ix_proof_lines_failure_code'), 'proof_lines', ['failure_code'], unique=False)
    op.create_index(op.f('ix_proof_lines_proof_id'), 'proof_lines', ['proof_id'], unique=False)
    op.create_index('ix_proof_lines_proof_number', 'proof_lines', ['proof_id', 'number'], unique=False)
    op.create_index('ix_proof_lines_rule', 'proof_lines', ['rule'], unique=False)
    op.create_index(op.f('ix_proof_lines_scope_id'), 'proof_lines', ['scope_id'], unique=False)
    op.create_index(op.f('ix_proof_lines_term_id'), 'proof_lines', ['term_id'], unique=False)
    op.create_index(op.f('ix_proof_lines_theorem_id'), 'proof_lines', ['theorem_id'], unique=False)
    op.create_index('uq_proof_lines_proof_position', 'proof_lines', ['proof_id', 'position'], unique=True)
    op.create_table('proof_references',
    sa.Column('proof_id', sa.Uuid(), nullable=False),
    sa.Column('references_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=64), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], name=op.f('fk_proof_references_proof_id_proofs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['references_id'], ['proofs.id'], name=op.f('fk_proof_references_references_id_proofs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proof_id', 'references_id', name=op.f('pk_proof_references'))
    )
    op.create_index('uq_proof_references_proof_alias', 'proof_references', ['proof_id', 'alias'], unique=True)
    op.create_table('theorems',
    sa.Column('formal_system_id', sa.Uuid(), nullable=False),
    sa.Column('proof_id', sa.Uuid(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('statement_term_id', sa.Uuid(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['formal_system_id'], ['formal_systems.id'], name=op.f('fk_theorems_formal_system_id_formal_systems'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proof_id'], ['proofs.id'], name=op.f('fk_theorems_proof_id_proofs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_term_id'], ['terms.id'], name=op.f('fk_theorems_statement_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_theorems'))
    )
    op.create_index('ix_theorems_embedding', 'theorems', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_theorems_formal_system_id'), 'theorems', ['formal_system_id'], unique=False)
    op.create_index(op.f('ix_theorems_proof_id'), 'theorems', ['proof_id'], unique=False)
    op.create_index(op.f('ix_theorems_statement_term_id'), 'theorems', ['statement_term_id'], unique=False)
    op.create_table('glossary_entries',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('formalization_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('notion', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('term_id', sa.Uuid(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['formalization_id'], ['formalizations.id'], name=op.f('fk_glossary_entries_formalization_id_formalizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_glossary_entries_term_id_terms'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_glossary_entries'))
    )
    op.create_index(op.f('ix_glossary_entries_formalization_id'), 'glossary_entries', ['formalization_id'], unique=False)
    op.create_index(op.f('ix_glossary_entries_term_id'), 'glossary_entries', ['term_id'], unique=False)
    op.create_table('proof_line_antecedents',
    sa.Column('line_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), server_default='antecedent', nullable=False),
    sa.Column('antecedent_line_id', sa.Uuid(), nullable=True),
    sa.Column('antecedent_proof_id', sa.Uuid(), nullable=True),
    sa.Column('antecedent_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['antecedent_line_id'], ['proof_lines.id'], name=op.f('fk_proof_line_antecedents_antecedent_line_id_proof_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['antecedent_proof_id'], ['proofs.id'], name=op.f('fk_proof_line_antecedents_antecedent_proof_id_proofs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_id'], ['proof_lines.id'], name=op.f('fk_proof_line_antecedents_line_id_proof_lines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id', 'position', name=op.f('pk_proof_line_antecedents'))
    )
    op.create_index(op.f('ix_proof_line_antecedents_antecedent_line_id'), 'proof_line_antecedents', ['antecedent_line_id'], unique=False)
    op.create_index(op.f('ix_proof_line_antecedents_antecedent_proof_id'), 'proof_line_antecedents', ['antecedent_proof_id'], unique=False)
    # ### end Alembic commands ###

    # Hand-added, and hand-dropped in `downgrade` for the same reason: this
    # foreign key and `proofs.theorem_id` point at each other, so it is declared
    # `use_alter` (see `app/db/promoted_theorems.py`) and `create_table` leaves
    # it out. Added here, once both tables exist.
    op.create_foreign_key(
        op.f("fk_promoted_theorems_proved_by_id_proofs"),
        "promoted_theorems",
        "proofs",
        ["proved_by_id"],
        ["id"],
        ondelete="CASCADE",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_promoted_theorems_proved_by_id_proofs"),
        "promoted_theorems",
        type_="foreignkey",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proof_line_antecedents_antecedent_proof_id'), table_name='proof_line_antecedents')
    op.drop_index(op.f('ix_proof_line_antecedents_antecedent_line_id'), table_name='proof_line_antecedents')
    op.drop_table('proof_line_antecedents')
    op.drop_index(op.f('ix_glossary_entries_term_id'), table_name='glossary_entries')
    op.drop_index(op.f('ix_glossary_entries_formalization_id'), table_name='glossary_entries')
    op.drop_table('glossary_entries')
    op.drop_index(op.f('ix_theorems_statement_term_id'), table_name='theorems')
    op.drop_index(op.f('ix_theorems_proof_id'), table_name='theorems')
    op.drop_index(op.f('ix_theorems_formal_system_id'), table_name='theorems')
    op.drop_index('ix_theorems_embedding', table_name='theorems', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('theorems')
    op.drop_index('uq_proof_references_proof_alias', table_name='proof_references')
    op.drop_table('proof_references')
    op.drop_index('uq_proof_lines_proof_position', table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_theorem_id'), table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_term_id'), table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_scope_id'), table_name='proof_lines')
    op.drop_index('ix_proof_lines_rule', table_name='proof_lines')
    op.drop_index('ix_proof_lines_proof_number', table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_proof_id'), table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_failure_code'), table_name='proof_lines')
    op.drop_index(op.f('ix_proof_lines_definition_id'), table_name='proof_lines')
    op.drop_table('proof_lines')
    op.drop_index(op.f('ix_formalizations_statement_term_id'), table_name='formalizations')
    op.drop_index(op.f('ix_formalizations_reviewed_by_id'), table_name='formalizations')
    op.drop_index(op.f('ix_formalizations_proof_id'), table_name='formalizations')
    op.drop_index(op.f('ix_formalizations_formal_system_id'), table_name='formalizations')
    op.drop_index(op.f('ix_formalizations_document_id'), table_name='formalizations')
    op.drop_index(op.f('ix_formalizations_attested_by_id'), table_name='formalizations')
    op.drop_table('formalizations')
    op.drop_index('ix_theorem_assumptions_assumption', table_name='theorem_assumptions')
    op.drop_table('theorem_assumptions')
    op.drop_index('uq_system_relation_obligations_label', table_name='system_relation_obligations')
    op.drop_index(op.f('ix_system_relation_obligations_relation_id'), table_name='system_relation_obligations')
    op.drop_index(op.f('ix_system_relation_obligations_discharged_by_theorem_id'), table_name='system_relation_obligations')
    op.drop_table('system_relation_obligations')
    op.drop_index('uq_side_conditions_rule_root', table_name='side_conditions', postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.drop_index('uq_side_conditions_promoted_theorem_root', table_name='side_conditions', postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.drop_index('uq_side_conditions_definition_root', table_name='side_conditions', postgresql_where=sa.text('parent_id IS NULL'), sqlite_where=sa.text('parent_id IS NULL'))
    op.drop_index(op.f('ix_side_conditions_sort_symbol_id'), table_name='side_conditions')
    op.drop_index('ix_side_conditions_rule_kind', table_name='side_conditions')
    op.drop_index(op.f('ix_side_conditions_rule_id'), table_name='side_conditions')
    op.drop_index(op.f('ix_side_conditions_promoted_theorem_id'), table_name='side_conditions')
    op.drop_index(op.f('ix_side_conditions_parent_id'), table_name='side_conditions')
    op.drop_index('ix_side_conditions_definition_kind', table_name='side_conditions')
    op.drop_index(op.f('ix_side_conditions_definition_id'), table_name='side_conditions')
    op.drop_table('side_conditions')
    op.drop_index(op.f('ix_rule_bindings_symbol_id'), table_name='rule_bindings')
    op.drop_index(op.f('ix_rule_bindings_rule_id'), table_name='rule_bindings')
    op.drop_table('rule_bindings')
    op.drop_index(op.f('ix_rule_antecedents_term_id'), table_name='rule_antecedents')
    op.drop_index(op.f('ix_rule_antecedents_rule_id'), table_name='rule_antecedents')
    op.drop_table('rule_antecedents')
    op.drop_index('ix_proofs_title_trgm', table_name='proofs', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_proofs_theorem_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_slug'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_owner_id'), table_name='proofs')
    op.drop_index('ix_proofs_name_trgm', table_name='proofs', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_proofs_formal_system_id'), table_name='proofs')
    op.drop_index(op.f('ix_proofs_folder_id'), table_name='proofs')
    op.drop_index('ix_proofs_description_trgm', table_name='proofs', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_table('proofs')
    op.drop_index(op.f('ix_promoted_theorem_premises_theorem_id'), table_name='promoted_theorem_premises')
    op.drop_index(op.f('ix_promoted_theorem_premises_term_id'), table_name='promoted_theorem_premises')
    op.drop_table('promoted_theorem_premises')
    op.drop_index(op.f('ix_promoted_theorem_bindings_theorem_id'), table_name='promoted_theorem_bindings')
    op.drop_index(op.f('ix_promoted_theorem_bindings_symbol_id'), table_name='promoted_theorem_bindings')
    op.drop_table('promoted_theorem_bindings')
    op.drop_index(op.f('ix_production_binding_scopes_scoped_binding_id'), table_name='production_binding_scopes')
    op.drop_index(op.f('ix_production_binding_scopes_binding_id'), table_name='production_binding_scopes')
    op.drop_table('production_binding_scopes')
    op.drop_index(op.f('ix_line_parts_line_id'), table_name='line_parts')
    op.drop_table('line_parts')
    op.drop_index(op.f('ix_definition_fresh_term_id'), table_name='definition_fresh')
    op.drop_index(op.f('ix_definition_fresh_symbol_id'), table_name='definition_fresh')
    op.drop_index(op.f('ix_definition_fresh_definition_id'), table_name='definition_fresh')
    op.drop_table('definition_fresh')
    op.drop_index(op.f('ix_definition_bindings_symbol_id'), table_name='definition_bindings')
    op.drop_index(op.f('ix_definition_bindings_definition_id'), table_name='definition_bindings')
    op.drop_table('definition_bindings')
    op.drop_index(op.f('ix_assumptions_asserted_by_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_term_children_child_id'), table_name='term_children')
    op.drop_table('term_children')
    op.drop_index('uq_system_relation_symbols_source', table_name='system_relation_symbols')
    op.drop_index(op.f('ix_system_relation_symbols_relation_id'), table_name='system_relation_symbols')
    op.drop_table('system_relation_symbols')
    op.drop_index('uq_system_relation_sorts_source', table_name='system_relation_sorts')
    op.drop_index(op.f('ix_system_relation_sorts_relation_id'), table_name='system_relation_sorts')
    op.drop_table('system_relation_sorts')
    op.drop_index('uq_system_relation_extras_name', table_name='system_relation_extras')
    op.drop_index(op.f('ix_system_relation_extras_relation_id'), table_name='system_relation_extras')
    op.drop_table('system_relation_extras')
    op.drop_index(op.f('ix_rules_system_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_subproof_fresh_term_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_subproof_derive_term_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_subproof_assume_term_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_name'), table_name='rules')
    op.drop_index(op.f('ix_rules_label'), table_name='rules')
    op.drop_index(op.f('ix_rules_deduction_term_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index('uq_promoted_theorems_system_label', table_name='promoted_theorems')
    op.drop_index('ix_promoted_theorems_system_primitive', table_name='promoted_theorems')
    op.drop_index(op.f('ix_promoted_theorems_system_id'), table_name='promoted_theorems')
    op.drop_index(op.f('ix_promoted_theorems_statement_term_id'), table_name='promoted_theorems')
    op.drop_index(op.f('ix_promoted_theorems_proved_by_id'), table_name='promoted_theorems')
    op.drop_index(op.f('ix_promoted_theorems_label'), table_name='promoted_theorems')
    op.drop_table('promoted_theorems')
    op.drop_index(op.f('ix_production_bindings_symbol_id'), table_name='production_bindings')
    op.drop_index(op.f('ix_production_bindings_production_id'), table_name='production_bindings')
    op.drop_table('production_bindings')
    op.drop_index('uq_notation_rule_pins_rule_slot', table_name='notation_rule_pins')
    op.drop_index(op.f('ix_notation_rule_pins_rule_id'), table_name='notation_rule_pins')
    op.drop_table('notation_rule_pins')
    op.drop_index('uq_notation_rule_pieces_rule_position', table_name='notation_rule_pieces')
    op.drop_index(op.f('ix_notation_rule_pieces_rule_id'), table_name='notation_rule_pieces')
    op.drop_table('notation_rule_pieces')
    op.drop_index(op.f('ix_line_types_system_id'), table_name='line_types')
    op.drop_index(op.f('ix_line_types_logical_symbol_id'), table_name='line_types')
    op.drop_table('line_types')
    op.drop_index('ix_label_references_target', table_name='label_references')
    op.drop_index(op.f('ix_label_references_description_id'), table_name='label_references')
    op.drop_table('label_references')
    op.drop_index('ix_label_citations_work', table_name='label_citations')
    op.drop_index(op.f('ix_label_citations_description_id'), table_name='label_citations')
    op.drop_table('label_citations')
    op.drop_index(op.f('ix_label_attributions_who'), table_name='label_attributions')
    op.drop_index(op.f('ix_label_attributions_kind'), table_name='label_attributions')
    op.drop_index(op.f('ix_label_attributions_description_id'), table_name='label_attributions')
    op.drop_table('label_attributions')
    op.drop_index(op.f('ix_definitions_system_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_symbol_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_name'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_lower_term_id'), table_name='definitions')
    op.drop_index(op.f('ix_definitions_higher_term_id'), table_name='definitions')
    op.drop_table('definitions')
    op.drop_index(op.f('ix_axiom_bindings_symbol_id'), table_name='axiom_bindings')
    op.drop_index(op.f('ix_axiom_bindings_axiom_id'), table_name='axiom_bindings')
    op.drop_table('axiom_bindings')
    op.drop_index('uq_terms_system_digest', table_name='terms')
    op.drop_index('ix_terms_system_constructor', table_name='terms')
    op.drop_index('ix_terms_system_alpha_digest', table_name='terms')
    op.drop_index(op.f('ix_terms_literal'), table_name='terms')
    op.drop_index(op.f('ix_terms_formal_system_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index('uq_system_relations_source_target', table_name='system_relations')
    op.drop_index(op.f('ix_system_relations_target_system_id'), table_name='system_relations')
    op.drop_index('ix_system_relations_target_status', table_name='system_relations')
    op.drop_index(op.f('ix_system_relations_source_system_id'), table_name='system_relations')
    op.drop_table('system_relations')
    op.drop_index('uq_symbols_system_name', table_name='symbols')
    op.drop_index(op.f('ix_symbols_system_id'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_name'), table_name='symbols')
    op.drop_index(op.f('ix_symbols_member_of_union_id'), table_name='symbols')
    op.drop_table('symbols')
    op.drop_index(op.f('ix_proof_folders_slug'), table_name='proof_folders')
    op.drop_index(op.f('ix_proof_folders_parent_id'), table_name='proof_folders')
    op.drop_index(op.f('ix_proof_folders_owner_id'), table_name='proof_folders')
    op.drop_index(op.f('ix_proof_folders_formal_system_id'), table_name='proof_folders')
    op.drop_table('proof_folders')
    op.drop_index('uq_notation_rules_system_notation_name', table_name='notation_rules')
    op.drop_index(op.f('ix_notation_rules_formal_system_id'), table_name='notation_rules')
    op.drop_index(op.f('ix_notation_rules_constructor'), table_name='notation_rules')
    op.drop_table('notation_rules')
    op.drop_index('uq_notation_pieces_system_notation_constructor_position', table_name='notation_pieces')
    op.drop_index(op.f('ix_notation_pieces_formal_system_id'), table_name='notation_pieces')
    op.drop_table('notation_pieces')
    op.drop_index(op.f('ix_notation_brackets_system_id'), table_name='notation_brackets')
    op.drop_table('notation_brackets')
    op.drop_index('uq_label_descriptions_system_label', table_name='label_descriptions')
    op.drop_index('ix_label_descriptions_title_trgm', table_name='label_descriptions', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_label_descriptions_text_trgm', table_name='label_descriptions', postgresql_using='gin', postgresql_ops={'text': 'gin_trgm_ops'})
    op.drop_index('ix_label_descriptions_label_trgm', table_name='label_descriptions', postgresql_using='gin', postgresql_ops={'label': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_label_descriptions_formal_system_id'), table_name='label_descriptions')
    op.drop_table('label_descriptions')
    op.drop_index('ix_label_claims_system_subject', table_name='label_claims')
    op.drop_index('ix_label_claims_object_kind', table_name='label_claims')
    op.drop_index(op.f('ix_label_claims_formal_system_id'), table_name='label_claims')
    op.drop_table('label_claims')
    op.drop_index(op.f('ix_axioms_system_id'), table_name='axioms')
    op.drop_index(op.f('ix_axioms_name'), table_name='axioms')
    op.drop_index(op.f('ix_axioms_label'), table_name='axioms')
    op.drop_table('axioms')
    op.drop_index('uq_source_documents_identity', table_name='source_documents')
    op.drop_index(op.f('ix_source_documents_registered_by_id'), table_name='source_documents')
    op.drop_table('source_documents')
    op.drop_index(op.f('ix_oauth_accounts_user_id'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_oauth_name'), table_name='oauth_accounts')
    op.drop_index(op.f('ix_oauth_accounts_account_id'), table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('uq_formal_systems_owner_slug', table_name='formal_systems', postgresql_where=sa.text('owner_id IS NOT NULL'))
    op.drop_index(op.f('ix_formal_systems_slug'), table_name='formal_systems')
    op.drop_index(op.f('ix_formal_systems_owner_id'), table_name='formal_systems')
    op.drop_index(op.f('ix_formal_systems_inherits_from_id'), table_name='formal_systems')
    op.drop_table('formal_systems')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
