<script lang="ts">
	import { onMount } from 'svelte';
	import { theme } from '$lib/theme.svelte';

	// A faint, fixed, non-interactive Penrose (P3 rhombus) tiling drawn behind the
	// whole app. Generated by deflating Robinson triangles; we stroke each tile's
	// two equal legs (the rhombus edges) and skip the unequal base (the internal
	// diagonal), so adjacent tiles share edges and the lines join up cleanly.

	let canvas: HTMLCanvasElement;

	type P = { re: number; im: number };
	const c = (re: number, im: number): P => ({ re, im });
	const lerp = (a: P, b: P, t: number): P => c(a.re + (b.re - a.re) * t, a.im + (b.im - a.im) * t);
	const dist = (a: P, b: P) => Math.hypot(a.re - b.re, a.im - b.im);

	function tiles(w: number, h: number): [P, P, P][] {
		const phi = (1 + Math.sqrt(5)) / 2;
		const R = Math.hypot(w, h) * 0.66;
		let tris: [number, P, P, P][] = [];
		for (let i = 0; i < 10; i++) {
			let b = c(R * Math.cos(((2 * i - 1) * Math.PI) / 10), R * Math.sin(((2 * i - 1) * Math.PI) / 10));
			let d = c(R * Math.cos(((2 * i + 1) * Math.PI) / 10), R * Math.sin(((2 * i + 1) * Math.PI) / 10));
			if (i % 2 === 0) [b, d] = [d, b];
			tris.push([0, c(0, 0), b, d]);
		}
		for (let g = 0; g < 6; g++) {
			const nx: [number, P, P, P][] = [];
			for (const [col, A, B, D] of tris) {
				if (col === 0) {
					const Pt = lerp(A, B, 1 / phi);
					nx.push([0, D, Pt, B], [1, Pt, D, A]);
				} else {
					const Q = lerp(B, A, 1 / phi);
					const Rr = lerp(B, D, 1 / phi);
					nx.push([1, Rr, D, A], [1, Q, Rr, B], [0, Rr, Q, A]);
				}
			}
			tris = nx;
		}
		return tris.map(([, a, b, d]) => [a, b, d]);
	}

	function draw() {
		if (!canvas) return;
		const dpr = Math.min(window.devicePixelRatio || 1, 2);
		const w = window.innerWidth;
		const h = window.innerHeight;
		canvas.width = w * dpr;
		canvas.height = h * dpr;
		canvas.style.width = `${w}px`;
		canvas.style.height = `${h}px`;
		const ctx = canvas.getContext('2d');
		if (!ctx) return;
		ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
		ctx.clearRect(0, 0, w, h);

		const color =
			getComputedStyle(canvas).getPropertyValue('--penrose-line').trim() || 'rgba(43,38,32,0.09)';
		ctx.translate(w / 2, h / 2);
		ctx.lineWidth = 0.8;
		ctx.lineJoin = 'round';
		ctx.strokeStyle = color;

		for (const [a, b, d] of tiles(w, h)) {
			// Isosceles Robinson triangle: two equal legs are rhombus edges, the odd
			// side out is the internal diagonal — stroke the legs, skip the diagonal.
			const ab = dist(a, b);
			const bd = dist(b, d);
			const da = dist(d, a);
			const eq = (x: number, y: number) => Math.abs(x - y) < 1e-3 * Math.max(x, y);
			let legs: [P, P][];
			if (eq(ab, bd)) legs = [[a, b], [b, d]];
			else if (eq(bd, da)) legs = [[b, d], [d, a]];
			else legs = [[a, b], [d, a]];
			ctx.beginPath();
			for (const [p, q] of legs) {
				ctx.moveTo(p.re, p.im);
				ctx.lineTo(q.re, q.im);
			}
			ctx.stroke();
		}
		ctx.setTransform(1, 0, 0, 1, 0, 0);
	}

	// Redraw on theme change (line colour differs by theme) and on resize.
	$effect(() => {
		void theme.value;
		draw();
	});

	onMount(() => {
		const onResize = () => draw();
		window.addEventListener('resize', onResize);
		return () => window.removeEventListener('resize', onResize);
	});
</script>

<canvas bind:this={canvas} aria-hidden="true" class="pointer-events-none fixed inset-0 z-0"></canvas>
